### ISSUE TITLE
Does not properly escape $, making it tiresome for Powershell Snippets

### ISSUE THREAD

**Issue by futuremotiondev** [wenfangdu/vscode-snippet-generator#1]
I'm building a repository of PowerShell scripts and I really love your addon, but it does not add the required "\\\\" before a dollar sign. This means I have to go through and manually add escape characters for each snippet since all PS variables are preceded with $. Would be great if you supported this.

Not to detract from your hard work. It's an excellent extension.

**Comment by wenfangdu** [comment]
@visusys This has been fixed in the latest version, please let me know if it's not working for you.
