### ISSUE TITLE
make extension available on `https://open-vsx.org/`

### ISSUE THREAD

**Issue by gm0stache** [wenfangdu/vscode-snippet-generator#10]
hi there!
the extension was highly recommended to me, but i find myself to be currently unable to install it in [vs-codium](https://vscodium.com/) since they are using open-vsx as the extension source.

-> would it be possible to provide the extension there too?

br and thanks for you work!

gabriel

**Comment by silopolis** [comment]
Yes please :pray:

**Comment by wenfangdu** [comment]
@JustAGabriel @silopolis Thanks for reporting, I've published it [here](https://open-vsx.org/extension/wenfangdu/snippet-generator), please let me know if there's any issue.

**Comment by gm0stache** [comment]
wow, thank you so much!
first download is mine 😁

**Comment by silopolis** [comment]
Awesome thank you!
Second to the party 🎉😉
