### ISSUE TITLE
How to use a variable in AL with Quotation Marks (")

### ISSUE THREAD

**Issue by adoorn** [wenfangdu/vscode-snippet-generator#11]
How to use a variable in AL with Quotation Marks (") So for example DocumentLine.SetRange("Document Type"...

**Comment by wenfangdu** [comment]
@adoorn Hi, please follow [the demo gif](https://github.com/wenfangdu/vscode-snippet-generator#snippet-generator), or [the written steps](https://github.com/wenfangdu/vscode-snippet-generator/pull/9).
