### ISSUE TITLE
Add a comma "," at the end of the snippet

### ISSUE THREAD

**Issue by PavelDvorak** [wenfangdu/vscode-snippet-generator#12]
Hello! 
Usually, a snippet is followed by other snippets, or is inserted between other snippets. Perhaps add a comma at the end of the snippet?

That is, replace this line:
https://github.com/wenfangdu/vscode-snippet-generator/blob/6f6425c36980692327b96c0a3ecb27b91dcf4149/extension.js#L71

with:
`.join('\n') + ","`
(sorry, cannot make a PR)

**Comment by wenfangdu** [comment]
@PavelDvorak Released in v0.3.8, if you like the extension, don't forget to leave a ⭐️ [here](https://github.com/wenfangdu/vscode-snippet-generator) :).

**Comment by PavelDvorak** [comment]
thanks @wenfangdu, works as expected. :+1: :bowing_man:
