### ISSUE TITLE
Is there any guide how to use this? 

### ISSUE THREAD

**Issue by murugappanrm** [wenfangdu/vscode-snippet-generator#2]
Hi,

Does anyone know how to use this extension??

**Comment by wenfangdu** [comment]
@murugappanrm Hi, please select the code first and use the command "Generate Snippet", and follow the prompts.

**Comment by murugappanrm** [comment]
Hi @wenfangdu 

Thank you for your reply. I finally figured what this extension does. It is intended to take a part of the code in a file and generate a snippet which them copied to clipboard. I had to paste the generated snippet and make changes if needed then save. I still working on it.

Perhaps the documentation could have been more elaborate with explanation. I am sure you understand that not all of us are as well versed with vscode and snippets. 

Thank you so much.
