### ISSUE TITLE
Not escaping "$"

### ISSUE THREAD

**Issue by CubeRanch** [wenfangdu/vscode-snippet-generator#3]
In PHP, when the selected code contains "$", your extension strips it out while generating the snippet body.

**Comment by wenfangdu** [comment]
@CubeRanch Hello, thanks for the report, can you provide a minimal repro case?

**Comment by CubeRanch** [comment]
Hi,
I don't know what to tell you. My bit of test code had a php variable in it. I just generated the same snippet twice from that same code to paste in here and each time the $ was correctly escaped. I have no idea what caused it to be stripped out before. If it happens again I'll try to nail down the circumstances.
Thanks for the quick response.
Regards.
