### ISSUE TITLE
Minor, don't escape vscode snippet variables

### ISSUE THREAD

**Issue by azjps** [wenfangdu/vscode-snippet-generator#8]
[Vscode supports certain variables in snippets such as `$TM_FILEPATH`](https://code.visualstudio.com/docs/editor/userdefinedsnippets#_variables), it would be nice if the `$` was not escaped when generating a snippet for these variables.

I suppose there is some ambiguity about what to do here since some of the variable names like `$UUID`, `$RANDOM`, `$CURRENT_YEAR` etc could plausibly be used as variables, such as in a bash script. But I think at least the `$TM_*` variables are unlikely to be used elsewhere and may be commonly useful in various snippets.

**Comment by wenfangdu** [comment]
@azjps Thanks for the report, what does `TM` stand for?

**Comment by wenfangdu** [comment]
@azjps Thanks for the report, what does `TM` stand for? I guess `TransforM`?

**Comment by wenfangdu** [comment]
@azjps Thanks for the report, what does `TM` stand for? I guess "transform"?

**Comment by azjps** [comment]
@wenfangdu I believe `TM` stands for TextMate: https://macromates.com/textmate/manual/snippets#variables

**Comment by wenfangdu** [comment]
@azjps Feel free to send a PR.

**Comment by wenfangdu** [comment]
@azjps Hi, could you try v3.0.6 and see if it fits your need?

**Comment by wenfangdu** [comment]
@azjps Hi, could you try v0.3.6 and see if it fits your need?
